ALTER TABLE `users`
  COMMENT = '系统用户表',
  MODIFY COLUMN `id` VARCHAR(191) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `username` VARCHAR(191) NOT NULL COMMENT '登录用户名',
  MODIFY COLUMN `password` VARCHAR(191) NOT NULL COMMENT '登录密码',
  MODIFY COLUMN `nickname` VARCHAR(191) NULL COMMENT '用户昵称',
  MODIFY COLUMN `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间（东八区会话时间）',
  MODIFY COLUMN `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间（东八区会话时间）';

ALTER TABLE `menus`
  COMMENT = '系统菜单表',
  MODIFY COLUMN `id` INTEGER NOT NULL COMMENT '菜单ID',
  MODIFY COLUMN `parent_id` INTEGER NULL COMMENT '父级菜单ID',
  MODIFY COLUMN `title` VARCHAR(191) NOT NULL COMMENT '菜单标题',
  MODIFY COLUMN `name` VARCHAR(191) NOT NULL COMMENT '路由名称',
  MODIFY COLUMN `type` INTEGER NOT NULL COMMENT '菜单类型：1目录 2菜单 3按钮',
  MODIFY COLUMN `path` VARCHAR(191) NOT NULL COMMENT '访问路径',
  MODIFY COLUMN `menu_key` VARCHAR(191) NOT NULL COMMENT '权限标识',
  MODIFY COLUMN `icon` VARCHAR(191) NULL COMMENT '图标',
  MODIFY COLUMN `layout` VARCHAR(191) NULL COMMENT '布局标识',
  MODIFY COLUMN `is_visible` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否显示',
  MODIFY COLUMN `component` VARCHAR(191) NOT NULL COMMENT '前端组件路径',
  MODIFY COLUMN `redirect` VARCHAR(191) NULL COMMENT '重定向路径',
  MODIFY COLUMN `meta` JSON NULL COMMENT '菜单元数据',
  MODIFY COLUMN `sort` INTEGER NOT NULL DEFAULT 0 COMMENT '排序值',
  MODIFY COLUMN `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间（东八区会话时间）',
  MODIFY COLUMN `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间（东八区会话时间）';

ALTER TABLE `dictionaries`
  COMMENT = '系统字典表',
  MODIFY COLUMN `id` VARCHAR(191) NOT NULL COMMENT '字典ID',
  MODIFY COLUMN `parent_id` VARCHAR(191) NULL COMMENT '父级字典ID',
  MODIFY COLUMN `weight` INTEGER NOT NULL COMMENT '权重',
  MODIFY COLUMN `name` VARCHAR(191) NOT NULL COMMENT '字典名称',
  MODIFY COLUMN `tenant_id` VARCHAR(191) NULL COMMENT '租户ID',
  MODIFY COLUMN `dict_label` VARCHAR(191) NOT NULL COMMENT '字典标签',
  MODIFY COLUMN `dict_value` VARCHAR(191) NOT NULL COMMENT '字典值',
  MODIFY COLUMN `category` VARCHAR(191) NOT NULL COMMENT '字典分类',
  MODIFY COLUMN `sort_code` INTEGER NOT NULL COMMENT '排序编码',
  MODIFY COLUMN `delete_flag` VARCHAR(191) NOT NULL COMMENT '删除标记',
  MODIFY COLUMN `create_time` VARCHAR(191) NULL COMMENT '业务创建时间',
  MODIFY COLUMN `create_user` VARCHAR(191) NULL COMMENT '业务创建人',
  MODIFY COLUMN `update_time` VARCHAR(191) NULL COMMENT '业务更新时间',
  MODIFY COLUMN `update_user` VARCHAR(191) NULL COMMENT '业务更新人',
  MODIFY COLUMN `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间（东八区会话时间）',
  MODIFY COLUMN `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间（东八区会话时间）';

ALTER TABLE `roles`
  COMMENT = '系统角色表',
  MODIFY COLUMN `id` VARCHAR(191) NOT NULL COMMENT '角色ID',
  MODIFY COLUMN `name` VARCHAR(191) NOT NULL COMMENT '角色名称',
  MODIFY COLUMN `code` VARCHAR(191) NOT NULL COMMENT '角色编码',
  MODIFY COLUMN `sort` INTEGER NOT NULL DEFAULT 0 COMMENT '排序值',
  MODIFY COLUMN `status` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '状态：1启用 0停用',
  MODIFY COLUMN `data_scope` VARCHAR(191) NOT NULL DEFAULT 'ALL' COMMENT '数据权限范围',
  MODIFY COLUMN `remark` VARCHAR(191) NULL COMMENT '备注',
  MODIFY COLUMN `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间（东八区会话时间）',
  MODIFY COLUMN `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间（东八区会话时间）';

ALTER TABLE `departments`
  COMMENT = '系统部门表',
  MODIFY COLUMN `id` INTEGER NOT NULL COMMENT '部门ID',
  MODIFY COLUMN `parent_id` INTEGER NULL COMMENT '父级部门ID',
  MODIFY COLUMN `name` VARCHAR(191) NOT NULL COMMENT '部门名称',
  MODIFY COLUMN `code` VARCHAR(191) NOT NULL COMMENT '部门编码',
  MODIFY COLUMN `leader` VARCHAR(191) NULL COMMENT '负责人',
  MODIFY COLUMN `phone` VARCHAR(191) NULL COMMENT '联系电话',
  MODIFY COLUMN `email` VARCHAR(191) NULL COMMENT '联系邮箱',
  MODIFY COLUMN `sort` INTEGER NOT NULL DEFAULT 0 COMMENT '排序值',
  MODIFY COLUMN `status` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '状态：1启用 0停用',
  MODIFY COLUMN `remark` VARCHAR(191) NULL COMMENT '备注',
  MODIFY COLUMN `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间（东八区会话时间）',
  MODIFY COLUMN `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间（东八区会话时间）';

ALTER TABLE `user_roles`
  COMMENT = '用户角色关联表',
  MODIFY COLUMN `user_id` VARCHAR(191) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `role_id` VARCHAR(191) NOT NULL COMMENT '角色ID',
  MODIFY COLUMN `assigned_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '分配时间（东八区会话时间）';

ALTER TABLE `role_menus`
  COMMENT = '角色菜单关联表',
  MODIFY COLUMN `role_id` VARCHAR(191) NOT NULL COMMENT '角色ID',
  MODIFY COLUMN `menu_id` INTEGER NOT NULL COMMENT '菜单ID',
  MODIFY COLUMN `assigned_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '分配时间（东八区会话时间）';

ALTER TABLE `role_department_scopes`
  COMMENT = '角色数据权限部门关联表',
  MODIFY COLUMN `role_id` VARCHAR(191) NOT NULL COMMENT '角色ID',
  MODIFY COLUMN `department_id` INTEGER NOT NULL COMMENT '部门ID',
  MODIFY COLUMN `assigned_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '分配时间（东八区会话时间）';

ALTER TABLE `system_configs`
  COMMENT = '系统配置表',
  MODIFY COLUMN `id` VARCHAR(191) NOT NULL COMMENT '配置ID',
  MODIFY COLUMN `config_key` VARCHAR(191) NOT NULL COMMENT '配置键',
  MODIFY COLUMN `config_name` VARCHAR(191) NOT NULL COMMENT '配置名称',
  MODIFY COLUMN `config_value` VARCHAR(191) NOT NULL COMMENT '配置值',
  MODIFY COLUMN `value_type` VARCHAR(191) NOT NULL DEFAULT 'string' COMMENT '值类型',
  MODIFY COLUMN `remark` VARCHAR(191) NULL COMMENT '备注',
  MODIFY COLUMN `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间（东八区会话时间）',
  MODIFY COLUMN `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间（东八区会话时间）';

ALTER TABLE `notices`
  COMMENT = '通知公告表',
  MODIFY COLUMN `id` VARCHAR(191) NOT NULL COMMENT '公告ID',
  MODIFY COLUMN `title` VARCHAR(191) NOT NULL COMMENT '公告标题',
  MODIFY COLUMN `content` VARCHAR(191) NOT NULL COMMENT '公告内容',
  MODIFY COLUMN `type` VARCHAR(191) NOT NULL COMMENT '公告类型',
  MODIFY COLUMN `status` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '发布状态：1已发布 0未发布',
  MODIFY COLUMN `publisher` VARCHAR(191) NULL COMMENT '发布人',
  MODIFY COLUMN `published_at` TIMESTAMP(3) NULL COMMENT '发布时间（东八区会话时间）',
  MODIFY COLUMN `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间（东八区会话时间）',
  MODIFY COLUMN `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间（东八区会话时间）';
