export const SUPER_ADMIN_ROLE_CODE = 'super_admin';

export const ROLE_DATA_SCOPE_ALL = 'ALL';
export const ROLE_DATA_SCOPE_DEPARTMENT = 'DEPARTMENT';
export const ROLE_DATA_SCOPE_DEPARTMENT_AND_CHILDREN =
  'DEPARTMENT_AND_CHILDREN';
export const ROLE_DATA_SCOPE_SELF = 'SELF';
export const ROLE_DATA_SCOPE_CUSTOM = 'CUSTOM';

export const ROLE_DATA_SCOPE_VALUES = [
  ROLE_DATA_SCOPE_ALL,
  ROLE_DATA_SCOPE_DEPARTMENT,
  ROLE_DATA_SCOPE_DEPARTMENT_AND_CHILDREN,
  ROLE_DATA_SCOPE_SELF,
  ROLE_DATA_SCOPE_CUSTOM
] as const;

export type RoleDataScope = (typeof ROLE_DATA_SCOPE_VALUES)[number];
