export const NOTICE_PUBLISH_SCOPE_TENANT_ALL = 'TENANT_ALL';
export const NOTICE_PUBLISH_SCOPE_ROLE = 'ROLE';
export const NOTICE_PUBLISH_SCOPE_DEPARTMENT = 'DEPARTMENT';

export const NOTICE_PUBLISH_SCOPE_VALUES = [
  NOTICE_PUBLISH_SCOPE_TENANT_ALL,
  NOTICE_PUBLISH_SCOPE_ROLE,
  NOTICE_PUBLISH_SCOPE_DEPARTMENT
] as const;

export type NoticePublishScope = (typeof NOTICE_PUBLISH_SCOPE_VALUES)[number];
