export {
  ROLE_DATA_SCOPE_ALL,
  ROLE_DATA_SCOPE_CUSTOM,
  ROLE_DATA_SCOPE_DEPARTMENT,
  ROLE_DATA_SCOPE_DEPARTMENT_AND_CHILDREN,
  ROLE_DATA_SCOPE_SELF,
  ROLE_DATA_SCOPE_VALUES,
  SUPER_ADMIN_ROLE_CODE,
  type RoleDataScope
} from '../../../shared/constants/access.constants';
