import { HttpStatus } from '@nestjs/common';

export const BUSINESS_ERROR_CODES = {
  AUTH_LOGIN_FAILED: 1011001,
  AUTH_ACCOUNT_DISABLED: 1011002,
  AUTH_TOKEN_EXPIRED: 1011007,
  AUTH_TOKEN_INVALID: 1011008,

  PERMISSION_DENIED: 1012001,
  MENU_PERMISSION_DENIED: 1012002,
  DATA_SCOPE_DENIED: 1012003,
  DATA_SCOPE_CONFIG_INVALID: 1012004,
  ROLE_DISABLED: 1012005,

  TENANT_NOT_FOUND: 1013001,
  TENANT_DISABLED: 1013002,
  TENANT_EXPIRED: 1013003,
  TENANT_ACCESS_DENIED: 1013004,
  TENANT_PACKAGE_NOT_FOUND: 1013005,
  TENANT_PACKAGE_IN_USE: 1013006,

  USER_NOT_FOUND: 1014001,
  ROLE_NOT_FOUND: 1014002,
  MENU_NOT_FOUND: 1014003,
  DEPARTMENT_NOT_FOUND: 1014004,
  DICTIONARY_NOT_FOUND: 1014005,
  CONFIG_NOT_FOUND: 1014006,
  NOTICE_NOT_FOUND: 1014007,
  SYSTEM_LOG_NOT_FOUND: 1014008,
  MENU_HIERARCHY_INVALID: 1014009,

  FILE_NOT_FOUND: 1015001,
  FILE_UPLOAD_FAILED: 1015002,
  FILE_DELETE_FAILED: 1015003,

  REQUEST_PARAMS_INVALID: 1016001,
  DATA_ALREADY_EXISTS: 1016002,
  STATUS_NOT_ALLOWED: 1016003
} as const;

export type BusinessErrorCode =
  (typeof BUSINESS_ERROR_CODES)[keyof typeof BUSINESS_ERROR_CODES];

export const BUSINESS_ERROR_MESSAGE_MAP: Record<BusinessErrorCode, string> = {
  [BUSINESS_ERROR_CODES.AUTH_LOGIN_FAILED]: '用户名或密码错误',
  [BUSINESS_ERROR_CODES.AUTH_ACCOUNT_DISABLED]: '当前账号已被禁用',
  [BUSINESS_ERROR_CODES.AUTH_TOKEN_EXPIRED]: '登录已过期，请重新登录',
  [BUSINESS_ERROR_CODES.AUTH_TOKEN_INVALID]: '登录状态无效，请重新登录',

  [BUSINESS_ERROR_CODES.PERMISSION_DENIED]: '当前账号没有此操作权限',
  [BUSINESS_ERROR_CODES.MENU_PERMISSION_DENIED]: '当前账号没有此菜单权限',
  [BUSINESS_ERROR_CODES.DATA_SCOPE_DENIED]: '当前账号没有此数据权限',
  [BUSINESS_ERROR_CODES.DATA_SCOPE_CONFIG_INVALID]: '数据权限范围配置不合法',
  [BUSINESS_ERROR_CODES.ROLE_DISABLED]: '当前账号角色已失效',

  [BUSINESS_ERROR_CODES.TENANT_NOT_FOUND]: '租户不存在',
  [BUSINESS_ERROR_CODES.TENANT_DISABLED]: '当前租户已被禁用',
  [BUSINESS_ERROR_CODES.TENANT_EXPIRED]: '当前租户已过期',
  [BUSINESS_ERROR_CODES.TENANT_ACCESS_DENIED]: '当前账号不能访问该租户',
  [BUSINESS_ERROR_CODES.TENANT_PACKAGE_NOT_FOUND]: '租户套餐不存在',
  [BUSINESS_ERROR_CODES.TENANT_PACKAGE_IN_USE]:
    '租户套餐已被租户使用，无法删除',

  [BUSINESS_ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [BUSINESS_ERROR_CODES.ROLE_NOT_FOUND]: '角色不存在',
  [BUSINESS_ERROR_CODES.MENU_NOT_FOUND]: '菜单不存在',
  [BUSINESS_ERROR_CODES.DEPARTMENT_NOT_FOUND]: '部门不存在',
  [BUSINESS_ERROR_CODES.DICTIONARY_NOT_FOUND]: '字典不存在',
  [BUSINESS_ERROR_CODES.CONFIG_NOT_FOUND]: '系统配置不存在',
  [BUSINESS_ERROR_CODES.NOTICE_NOT_FOUND]: '通知公告不存在',
  [BUSINESS_ERROR_CODES.SYSTEM_LOG_NOT_FOUND]: '系统日志不存在',
  [BUSINESS_ERROR_CODES.MENU_HIERARCHY_INVALID]: '菜单层级关系不合法',

  [BUSINESS_ERROR_CODES.FILE_NOT_FOUND]: '文件不存在',
  [BUSINESS_ERROR_CODES.FILE_UPLOAD_FAILED]: '文件上传失败',
  [BUSINESS_ERROR_CODES.FILE_DELETE_FAILED]: '文件删除失败',

  [BUSINESS_ERROR_CODES.REQUEST_PARAMS_INVALID]: '请求参数校验失败',
  [BUSINESS_ERROR_CODES.DATA_ALREADY_EXISTS]: '数据已存在，请勿重复创建',
  [BUSINESS_ERROR_CODES.STATUS_NOT_ALLOWED]: '当前状态不允许执行该操作'
};

export const BUSINESS_ERROR_HTTP_STATUS_MAP: Record<BusinessErrorCode, number> =
  {
    [BUSINESS_ERROR_CODES.AUTH_LOGIN_FAILED]: HttpStatus.UNAUTHORIZED,
    [BUSINESS_ERROR_CODES.AUTH_ACCOUNT_DISABLED]: HttpStatus.FORBIDDEN,
    [BUSINESS_ERROR_CODES.AUTH_TOKEN_EXPIRED]: HttpStatus.UNAUTHORIZED,
    [BUSINESS_ERROR_CODES.AUTH_TOKEN_INVALID]: HttpStatus.UNAUTHORIZED,

    [BUSINESS_ERROR_CODES.PERMISSION_DENIED]: HttpStatus.FORBIDDEN,
    [BUSINESS_ERROR_CODES.MENU_PERMISSION_DENIED]: HttpStatus.FORBIDDEN,
    [BUSINESS_ERROR_CODES.DATA_SCOPE_DENIED]: HttpStatus.FORBIDDEN,
    [BUSINESS_ERROR_CODES.DATA_SCOPE_CONFIG_INVALID]: HttpStatus.BAD_REQUEST,
    [BUSINESS_ERROR_CODES.ROLE_DISABLED]: HttpStatus.FORBIDDEN,

    [BUSINESS_ERROR_CODES.TENANT_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.TENANT_DISABLED]: HttpStatus.FORBIDDEN,
    [BUSINESS_ERROR_CODES.TENANT_EXPIRED]: HttpStatus.FORBIDDEN,
    [BUSINESS_ERROR_CODES.TENANT_ACCESS_DENIED]: HttpStatus.FORBIDDEN,
    [BUSINESS_ERROR_CODES.TENANT_PACKAGE_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.TENANT_PACKAGE_IN_USE]: HttpStatus.CONFLICT,

    [BUSINESS_ERROR_CODES.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.ROLE_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.MENU_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.DEPARTMENT_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.DICTIONARY_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.CONFIG_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.NOTICE_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.SYSTEM_LOG_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.MENU_HIERARCHY_INVALID]: HttpStatus.BAD_REQUEST,

    [BUSINESS_ERROR_CODES.FILE_NOT_FOUND]: HttpStatus.NOT_FOUND,
    [BUSINESS_ERROR_CODES.FILE_UPLOAD_FAILED]: HttpStatus.BAD_REQUEST,
    [BUSINESS_ERROR_CODES.FILE_DELETE_FAILED]: HttpStatus.BAD_REQUEST,

    [BUSINESS_ERROR_CODES.REQUEST_PARAMS_INVALID]:
      HttpStatus.UNPROCESSABLE_ENTITY,
    [BUSINESS_ERROR_CODES.DATA_ALREADY_EXISTS]: HttpStatus.CONFLICT,
    [BUSINESS_ERROR_CODES.STATUS_NOT_ALLOWED]: HttpStatus.BAD_REQUEST
  };
